# Generated by Django 3.1.7 on 2021-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_starter', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField()),
                ('pokedex_entry', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
