# Generated by Django 3.1.7 on 2021-03-24 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0002_pokemon_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_pokemon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pokemon', to=settings.AUTH_USER_MODEL),
        ),
    ]
